# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: 'Nuget.config'

- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: 'src/Foundation'

- task: Gulp@1
  inputs:
    gulpFile: 'src/Foundation/gulpfile.js'
    targets: 'default'
    enableCodeCoverage: false
    
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Foundation'
    organization: 'episerver'
    scannerMode: 'MSBuild'
    projectKey: 'epi-foundation'
    projectName: 'Foundation'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:SkipInvalidConfigurations=true'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: SonarCloudAnalyze@1
- task: VSBuild@1
  inputs:
    solution: 'src/Foundation/Foundation.csproj'
    msbuildArgs: '/t:Metrics /p:MetricsOutputFile=$(Build.ArtifactStagingDirectory)/Foundation.Metrics.xml'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'